name: Publish release

on:
  push:
    branches:
      - 'master'

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout latest code'
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: 'Configure git'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: 'Grant Permissions to gradlew'
        run: chmod +x gradlew

      - name: 'Publish release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          ./gradlew release -Dorg.ajoberstar.grgit.auth.username=$GITHUB_ACTOR -Dorg.ajoberstar.grgit.auth.password=$GITHUB_TOKEN --info --stacktrace