name: Publish release

on:
  push:
    branches:
      - 'master'

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout latest code'
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: 'Grant Permissions to gradlew'
        run: chmod +x gradlew

      - name: 'Publish release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          ./gradlew release --info --stacktrace